### ISSUE TITLE
Invalid Argument - acquire_data.py

### ISSUE THREAD

**Issue by ujwalakoriraj** [Paulymorphous/skeyenet#12]
I have added the exact path to 'link_file_images', 'link_file_targets' and 'output_directory' variables, in the acquire_data.py program. I am encountering the following error(please help):

  `File "D:\python\building_detection\8_building\skeyenet-master\Src\acquire_data.py", line 38, in download_images
    urllib.request.urlretrieve(image_link, image_path)

  File "C:\Users\rajak\anaconda3\envs\road\lib\urllib\request.py", line 257, in urlretrieve
    tfp = open(filename, 'wb')

OSError: [Errno 22] Invalid argument: 'D:/python/building_detection/8_building/skeyenet-master/Data/MassachusettsRoads/Images/10078660_15.tiff\n'`

**Comment by RexMello** [comment]
> While running the acquire_data.py to download the dataset, I ran into this error (is it because ' /n ' is taken at the end of the URL of the image to be downloaded?):
> 
> `Downloading Images 0%| | 0/1110 [00:00<?, ?it/s] Traceback (most recent call last):
> 
> File "D:\python\building_detection\8_building\skeyenet-master\Src\acquire_data.py", line 58, in download_images(link_file_images, output_directory, "Images")
> 
> File "D:\python\building_detection\8_building\skeyenet-master\Src\acquire_data.py", line 38, in download_images urllib.request.urlretrieve(image_link, image_path)
> 
> File "C:\Users\rajak\anaconda3\envs\road\lib\urllib\request.py", line 257, in urlretrieve tfp = open(filename, 'wb')
> 
> OSError: [Errno 22] Invalid argument: 'D:/python/building_detection/8_building/skeyenet-master/Data/MassachusettsRoads/Images/10078660_15.tiff\n'`

Had same issue and I solved it by removing \n. Find the variable that stores the full address and do this

`variable = variable.replace('\n','')`
